trigger:
  branches:
    include:
      - 'master'

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'macos-10.14'


variables:
  system.debug: true

steps:
      
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: ':sessionize:lib:packForXCode'
      displayName: 'Pack For Xcode'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'sessionize/lib/build/bin/ios/debugFramework/lib.framework '
      artifactName: drop

  - script: /usr/local/bin/pod deintegrate
    workingDirectory: 'iosApp'
    displayName: 'pod deintegrate'
    
  - script: /usr/local/bin/pod install
    workingDirectory: 'iosApp'
    displayName: 'pod install'

  - task: Xcode@5
    inputs:
      actions: 'clean build'
      scheme: 'iosApp'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      workingDirectory: 'iosApp'
      xcWorkspacePath: 'iosApp/iosApp.xcworkspace'
      xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
      displayName: 'Building For iOS'

  - task: Xcode@5
    inputs:
      actions: 'test'
      scheme: 'iosApp'
      sdk: 'iphonesimulator'
      configuration: 'Debug'
      workingDirectory: 'iosApp'
      xcWorkspacePath: 'iosApp/iosApp.xcworkspace'
      xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
      packageApp: false
      destinationSimulators: 'iPhone 7'
      destinationTypeOption: 'simulators'
      destinationPlatformOption: 'iOS'
      signingOption: "auto"
      useXcpretty: true
      publishJUnitResults: true
      displayName: 'Running XCTest/XCUITest'