name: ktlint

on:
  pull_request:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: run ktlint
        run: ./gradlew ktlintCheck
